### ISSUE TITLE
Date conversion failes

### ISSUE THREAD

**Issue by niklasCarstensen** [WFCD/Warframe.NET#13]
This is a really cool project but when I try to run it I only get a "Unexpected character encountered while parsing value: {. Path 'Alerts[0].Activation', line 1, position 6576."

Which points to ""Activation":{"$date":{"$numberLong":"1543679128601"}}" in the json. 
So there is some error with the date conversion here or Im missing something.

**Comment by Erlite** [comment]
Hey! I'll check it out, but this project is currently under rewrite. You can check the rewrite branch for more details. The current implementation lacks a lot of things and is generally bad.

**Comment by Erlite** [comment]
@niklasCarstensen can you send the full stacktrace?

**Comment by TobiTenno** [comment]
@niklasCartensen you need to use api.warframestat.us not the base worldstate from DE

**Comment by niklasCarstensen** [comment]
Ohh I didn't expect DE to have multiple worldstate jsons
Also thanks for answering so fast, I didn't expect that either. ^^

Im using your library [here](https://github.com/niklasCarstensen/warframe-alerts-win) if you wanna look over it.
I hope Im using the license correctly.

**Comment by niklasCarstensen** [comment]
The banner was still there from the fork but I removed it now and I also added the license to this project into the readme now

**Comment by Erlite** [comment]
Looks good, however, I do think that the copyright has to be included? I'm bad with licenses so don't quote me on this ^^'

**Comment by TobiTenno** [comment]
oh, i see now. you're writing an update for an existing C# app one of ours had made some time ago.

**Comment by TobiTenno** [comment]
If you just wanna write a PR on it, we can probably rope you in and let you just help maintain it
